import type { Metadata } from "next";
import { Inter, Roboto_Serif } from "next/font/google";
import "./style/globals.css";
import "./style/toastfy.css";
import "./style/reset.css";
import { Providers } from "@/providers";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto_Serif({
  subsets: ["latin"],
  weight: "600",
  style: "italic",
});

export const metadata: Metadata = {
  title: "Clients & Contacts",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/svg+xml" href="/HeadIcon.svg" />
      </head>
      <Providers>
        <body className={roboto.className}>
          <ToastContainer theme="dark" autoClose={1500} stacked />
          {children}
        </body>
      </Providers>
    </html>
  );
}
